services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env
volumes:
  postgres_data:
